"""empty message

Revision ID: f8071dea11a7
Revises: 2c57bb12ced3
Create Date: 2019-06-01 02:02:46.502919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8071dea11a7'
down_revision = '2c57bb12ced3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'is_public')
    # ### end Alembic commands ###
